# -*- coding: utf-8 -*-
"""app.py_streamlit_cloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDRt8SmPPM20HS4fyCTQUQh2UloGcPF_
"""

import streamlit as st
from models.main import load_model, preprocess_image, predict_image, class_names

# Chargement du modèle
st.title("Reconnaissance de Maladies des Plantes")
model_choice = st.selectbox("Choisissez un modèle :", ["Model 1", "Model 2", "Model 3", "Model 4"])

models = {
    "Model 1": "C:/Users/anasm/Downloads/Reco-Plantes/models/Anas_Essai_1_MOB_L2.keras",
    "Model 2": "C:/Users/anasm/Downloads/Reco-Plantes/models/Anas_Essai_1_MOB_Repeat.keras",
    "Model 3": "C:/Users/anasm/Downloads/Reco-Plantes/models/leila_best_model_cnn_TEM3.keras",
    "Model 4": "C:/Users/anasm/Downloads/Reco-Plantes/models/model_cnn_4_best.keras",
}
model_path = models[model_choice]
model = load_model(model_path)

# Téléchargement de l'image
uploaded_file = st.file_uploader("Téléchargez une image", type=["jpg", "png"])
if uploaded_file is not None:
    st.image(uploaded_file, caption="Image téléchargée", use_column_width=True)
    input_shape = model.input_shape[1:3]
    image_array = preprocess_image(uploaded_file, target_size=input_shape)
    predicted_class, confidence = predict_image(model, image_array)
    st.success(f"Résultat : {predicted_class} ({confidence:.2f}%)")